import { useLanguage } from "../contexts/LanguageContext";
import { Card } from "../components/ui/Card";
import { VerifiedBadge, DemoDataBadge } from "../components/common/VerificationBadges";

export default function DataSources() {
  const { t } = useLanguage();

  return (
    <div className="space-y-6 pt-1">
      <section>
        <h1 className="font-display text-2xl font-semibold text-navy-800">{t("dataSources.title")}</h1>
        <p className="text-stone-500 mt-1">{t("dataSources.subtitle")}</p>
      </section>

      <Card className="space-y-3">
        <div className="flex items-center gap-2"><VerifiedBadge verified={true} /></div>
        <p className="text-sm text-navy-700">
          A record is marked <strong>Verified</strong> only when its details (name, phone, and location) come from an
          official source we can point to directly — such as a government health authority's own website or contact
          listing. In this prototype, that currently means Dhaka Medical College Hospital, Chittagong Medical College
          Hospital, the National Emergency Service (999), the National Health Helpline (16263), and the National
          Helpline for Violence Against Women & Children (109).
        </p>
      </Card>

      <Card className="space-y-3">
        <div className="flex items-center gap-2"><VerifiedBadge verified={false} /></div>
        <p className="text-sm text-navy-700">
          A record marked <strong>Needs Verification</strong> comes from a secondary source (like a hospital directory
          website) that we have not cross-checked against an official listing. Please confirm details independently
          before relying on them in an emergency.
        </p>
      </Card>

      <Card className="space-y-3">
        <div className="flex items-center gap-2"><DemoDataBadge /></div>
        <p className="text-sm text-navy-700">
          Records marked <strong>DEMO DATA</strong> are sample placeholders that demonstrate the app's architecture
          (filtering by division, facility type, ownership, etc.) across Bangladesh. They intentionally have no phone
          number or coordinates attached, because we don't have real, verifiable data for them yet. In a production
          deployment, these would be replaced by an import from the official DGHS / Ministry of Health and Family
          Welfare facility registry.
        </p>
      </Card>

      <Card className="space-y-2">
        <h2 className="font-semibold text-navy-800">Primary intended data source</h2>
        <p className="text-sm text-navy-700">
          Bangladesh Government / DGHS / Ministry of Health and Family Welfare Facility Registry — official records of
          hospitals, health complexes, clinics, diagnostic centers, and blood banks nationwide, including facility
          type, administrative location, and ownership. This prototype's data layer is structured to accept a full
          import from that registry (see server/src/repositories/facilities.repository.ts).
        </p>
      </Card>

      <Card className="space-y-2">
        <h2 className="font-semibold text-navy-800">AI-generated guidance</h2>
        <p className="text-sm text-navy-700">
          First-aid guidance, prescription explanations, and specialist suggestions are generated by Google Gemini
          under strict safety instructions (never diagnose, never prescribe, escalate when uncertain) and are
          validated against a strict schema before being shown. They are general safety information, not verified
          medical facts, and never replace professional care.
        </p>
      </Card>
    </div>
  );
}
